wireplumber.settings = {
  "node.stream.restore-target" = false,
  "linking.follow-default-target" = true,
  "linking.allow-moving-streams" = true,
  "bluetooth.autoswitch-to-headset-profile" = true
}
