general {
    lock_cmd = niri msg action ext-session-lock-v1-lock
    before_sleep_cmd = niri msg action ext-session-lock-v1-lock
}

listener {
    timeout = 300
    on-timeout = niri msg action turn-outputs-off
    on-resume = niri msg action turn-outputs-on
}

listener {
    timeout = 600
    on-timeout = niri msg action ext-session-lock-v1-lock
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}